version: '2'

services:
  activemq:
    image: rmohr/activemq:5.10.0
    container_name: activemqDocker3
    environment:
      - "TZ=Europe/Paris"
    volumes:
      - "./activemq/activemq.xml:/conf/activemq.xml"
    ports:
      - "61617:61616" # broker (admin:adminactivemq) (amq:amq)
      - "8162:8161"   # web    http://boot2docker:8161/admin (admin:admin)